### ISSUE TITLE
when clicking search button on nav bar, prepopulate search view with open jobs

### ISSUE THREAD

**Issue by dlum88** [daft-funk/shiftwerk#147]

**Comment by alexa-w** [comment]
just to make sure I have it right, what should it look like? Where do we see our search options and where do we see our results?

**Comment by dlum88** [comment]
Well so i was thinking when you click on the search button on the nav bar now, it'll take you to the search view and already prepopulate with some jobs near your location. That way a user could just scroll through and see what jobs are near them. Search options could be at the top which would allow them to be filtered? The other way would just a regular search where its empty and populates after the user clicks submit for their search terms

**Comment by alexa-w** [comment]
:+1: thanks for the clarity, friend
